### ISSUE TITLE
PS_ROUTE* configuration table values should be set

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#8] opened 2017-09-24 12:08 UTC
In the SEO&IUrl's page of your backoffice you have the schema of urls section where you can define how your url's should look like. These values are stored in the ps_configuration and the ps_configuration_lang tables in fields with names like PS_ROUTE_product_rule. The ps_configuration table contains the name and the ps_configuration_lang table the value.

In Prestashop by default there are no values in the ps_configuration_lang table for these settings and that is interpreted as them having the default values. However, in ThirtyBees it is obligatory that the ps_configuration_lang table values are set and the absence of those values is interpreted as empty values. With the obvious result as you try to save the values 
![thirty5](https://user-images.githubusercontent.com/13930107/30782387-b2f5a6f4-a131-11e7-8bbe-db52c4559ba6.jpg)

So I believe that the migration script should set these values when they are absent.

**Comment by firstred** [comment] 2017-09-24 19:57
> So I believe that the migration script should set these values when they are absent.

Thanks. It's the migration indeed, the old script it has ignores the `_lang` tables.

**Comment by Traumflug** [comment] 2018-12-08 12:42
This is a duplicate of https://github.com/thirtybees/thirtybees/issues/604 and was fixed. For the solution, see https://github.com/thirtybees/thirtybees/issues/604#issuecomment-445359057

**Closed as completed by Traumflug** 2018-12-08 12:42 UTC
