### ISSUE TITLE
Outdated cacert.pem causes migration errors

### ISSUE THREAD

**Issue by kozakhs** [thirtybees/psonesixmigrator#25] opened 2022-01-11 10:35 UTC
Hello,

when I click to "MIGRATE TO THIRTYBEES" button, it always results in this error:
"Error during download"

Full output of migration:

```
Archives will come from  and 
md5 hashes for core and extra should be resp.  and 
Directory tests complete.
Downloading from  and 
Files will be saved to /home/krpresta/public_html/administrace/psonesixmigrator/download/thirtybees-v.zip and /home/krpresta/public_html/administrace/psonesixmigrator/download/thirtybees-extra-v.zip
Downloads took 0 seconds.
Error during download
```

Thank you

**Comment by getdatakick** [comment] 2022-01-14 08:23
This looks like your server is misconfigured, and does not allow curl requests to third party servers. Please check with your hosting provider if php scripts can open api.thirtybees.com.

Anyway, if this is indeed the root cause of your problem, the error message should be very different

**Comment by kozakhs** [comment] 2022-01-14 09:11
Thank you for your response. I've checked it, but the server configuration is ok and php scripts are allowed to execute any curl request. However I've tried to dive into it and found out following... In file Upgrader.php, method checkTbVersion() there are errors in the GuzzleHttp promises:

```
....
private 'handlerContext' => 
            array (size=28)
              'errno' => int 60
              'error' => string 'SSL certificate problem: certificate has expired' (length=48)
              'url' => string 'https://api.thirtybees.com/migration/channels/alpha.json' (length=56)
...
```
So I rather guess there can be a SSL problem on thirtybees server side, but I may be wrong....

**Comment by getdatakick** [comment] 2022-01-14 09:18
No, it's not problem on server side. It's a truststore issue -- your server store does not trust new root certificate that is used to sign api.thirtybees.com certificate.

**Comment by getdatakick** [comment] 2022-01-14 09:20
This module comes with outdated cacert file. It needs to be updated to include new root authority certificates

**Comment by getdatakick** [comment] 2022-01-14 09:22
@kozakhs Until this issue is resolved, you can download up-to-date`cacert.pem` file from github thirtybees repository https://raw.githubusercontent.com/thirtybees/thirtybees/main/tools/cacert.pem -- use this file to overwrite the outdated file in psonesixmigrator module directory

**Comment by kozakhs** [comment] 2022-01-14 11:10
Thanks for the help! I've replaced the signing certificate with this new one and it works. I am closing this issue.

**Comment by getdatakick** [comment] 2022-01-14 12:29
I will keep this issue open to not forget about this issue. Should be fixed in next module update

**Comment by deweblooper** [comment] 2022-03-23 20:17
Hello Getdatakick, seems like some certificate is outdated again. even file in link to updated cacert.pem you posted is not helpful already.
I´ve been trying even any other pem founded, but without success.
Here is actualized cacert.pem [https://curl.se/docs/caextract.html](https://curl.se/docs/caextract.html) it works for Core updater module if you save it to /tools/ folder and set "Verify SSL certificates" to "Verify SSL using thirty bees trust store".
But after copying to "psonesixmigrator" folder this module won´t work again, on localhost also.
thank you

**Closed as completed** 2022-06-09 07:09 UTC
Labels: bug
